services:
  # 启动 Qdrant 向量数据库（开发版镜像）
  qdrant:
    image: qdrant/qdrant:dev
    container_name: qdrant
    ports:
      - "6333:6333"           # Qdrant HTTP & gRPC 默认端口
    volumes:
      - qdrant-data:/qdrant/storage
    restart: unless-stopped
    # 如需高级配置，可解开以下环境变量
    # environment:
    #   - QDRANT__STORAGE__PATH=/qdrant/storage
    #   - QDRANT__SERVICE__GRPC_PORT=6334

volumes:
  qdrant-data:
    driver: local

